
configuration: Debug

branches:
  only:
    - master
    - staging

image:
  - Visual Studio 2017

install: 
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build: 
  # Updates the version number in the .vsixmanifest and updates the AppVeyor build number to match
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion

build_script:
  cmd: >-
    msbuild /m /r /clp:v=m VsVim.sln /bl /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
  path: msbuild.binlog
  name: MSBuild Log

on_failure:
  appveyor PushArtifact msbuild.binlog

after_build:
  - Binaries\Debug\CleanVsix\net461\CleanVsix.exe Binaries\Debug\VsVim\VsVim.vsix

test_script:
  - cmd: '%xunit20%\xunit.console.x86.exe Binaries\Debug\VimCoreTest\net461\Vim.Core.UnitTest.dll -appveyor -noshadow'
  - cmd: '%xunit20%\xunit.console.x86.exe Binaries\Debug\VimWpfTest\net461\Vim.UI.Wpf.UnitTest.dll -appveyor -noshadow'
  - cmd: '%xunit20%\xunit.console.x86.exe Binaries\Debug\VsVimSharedTest\net461\Vim.VisualStudio.Shared.UnitTest.dll -appveyor -noshadow'
  - cmd: '%xunit20%\xunit.console.x86.exe Binaries\Debug\VsVim\net461\VsVim.UnitTest.dll -appveyor -noshadow'

after_test:
  # Pushes the compiled vsix to artifacts and publishes it to vsixgallery.com
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery
